# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the game reference lists as Markdown pages: docs/references/index.md and one page per topic.

Every entry gets a stable anchor, `<topic anchor>-<key>` (`characters.md#char-32`), so other pages, issues and mods
can link to it. The pages are generated: `coney-tools refs render` rewrites them and `--check` fails when one is out
of date with its YAML.

Research: docs/guides/research-workflow.md#reference-lists
"""

from __future__ import annotations

import re
import textwrap
from collections.abc import Sequence
from typing import Any

from coney_tools.refs import GAP_FIELDS, Field, Gaps, RefList, Topic, part_name

GENERATED = "<!-- Generated by `coney-tools refs render` from research/references/{key}.yaml. Do not edit. -->"
SPACE_SIGN = "␠"  # shows a meaningful space at the edge of a code span
IMAGE_WIDTH = 96  # pixels: the thumbnails are 256 x 256, shown small in tables


def slug(value: Any) -> str:
    """An anchor-safe form of a key: lower case, runs of other characters as one `-`."""
    text = f"{value:08x}" if isinstance(value, int) and value > 0xFFFF else str(value)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "x"


def anchor(topic: Topic, key: Any) -> str:
    """The anchor of an entry: `<prefix>-<slug(key)>`."""
    return f"{topic.anchor}-{slug(key)}"


def _escape(text: str) -> str:
    """Make prose safe inside a table cell: no pipes or line breaks."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _code(text: str) -> str:
    """A name as inline code (backticks inside are rare; a double fence handles them)."""
    text = _visible_edge_spaces(text.replace("|", "\\|"))
    return f"`` {text} ``" if "`" in text else f"`{text}`"


def _visible_edge_spaces(text: str) -> str:
    """`text` with each space at its start or end shown as the space sign (U+2420).

    A space at either end of a code span is invisible and markdownlint refuses it (MD038), but a tag such as
    `<COLOR ` has one that matters: it says the tag takes an argument.
    """
    core = text.strip(" ")
    if core == text:
        return text
    if not core:
        return SPACE_SIGN * len(text)
    start = text.index(core)
    return SPACE_SIGN * start + core + SPACE_SIGN * (len(text) - start - len(core))


def _number(value: float | int) -> str:
    """A number without trailing noise: ints as is, floats rounded to 4 significant decimals."""
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".") if value != int(value) else str(int(value))
    return str(value)


def cell(spec: Field, value: Any, topic_key: str = "", base: str = "") -> str:
    """One table cell for `value` of field `spec`; `base` prefixes relative links (`../` on a split list's page)."""
    if value is None or value == [] or value == {}:
        return ""
    if spec.name == "image":
        return f'![{_escape(str(value))}]({base}images/{value}){{ width="{IMAGE_WIDTH}" }}'
    if spec.name == "swatch":
        return f'<span style="display:inline-block;width:2em;height:1em;background:#{value[:6]}"></span>'
    if spec.link and isinstance(value, list):
        page, prefix = spec.link.split("#")
        return ", ".join(
            f"[{_number(v) if isinstance(v, (int, float)) else v}]({base}{page}#{prefix}-{slug(v)})" for v in value
        )
    if spec.link:
        page, prefix = spec.link.split("#")
        return f"[{_number(value) if isinstance(value, (int, float)) else value}]({base}{page}#{prefix}-{slug(value)})"
    if spec.kind == "hex" and isinstance(value, int):
        return _code(f"0x{value:08x}" if value > 0xFFFF else f"0x{value:04x}")
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return _number(value)
    if isinstance(value, dict):
        return ", ".join(f"{k} {_number(v) if isinstance(v, (int, float)) else v}" for k, v in value.items())
    if isinstance(value, list):
        parts = [_number(v) if isinstance(v, (int, float)) else _cell_list_item(v) for v in value]
        return ", ".join(parts)
    text = str(value)
    return _escape(text) if spec.curated or spec.prose else _code(text)


def _cell_list_item(value: Any) -> str:
    """One item of a list cell: names as code, nested lists in braces."""
    if isinstance(value, list):
        return "{" + ", ".join(_number(v) if isinstance(v, (int, float)) else str(v) for v in value) + "}"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k} {v}" for k, v in value.items()) + "}"
    return _code(str(value))


def _columns(topic: Topic, entries: Sequence[dict[str, Any]]) -> list[Field]:
    """The fields shown as columns: those with a heading that at least one entry fills."""
    shown = []
    for spec in topic.field_map().values():
        if spec.column is None or spec.name == topic.group_by:
            continue
        if spec.name == topic.key_field or any(entry.get(spec.name) not in (None, [], {}) for entry in entries):
            shown.append(spec)
    # The thumbnail goes right after the first column: these tables are wider than the page, so a picture in the last
    # column would only show after scrolling sideways. The first column keeps the row's anchor.
    images = [spec for spec in shown if spec.name == "image"]
    rest = [spec for spec in shown if spec.name != "image"]
    return rest[:1] + images + rest[1:]


def table(topic: Topic, entries: Sequence[dict[str, Any]], base: str = "") -> list[str]:
    """A Markdown table of `entries`, the first cell of each row carrying the entry's anchor."""
    columns = _columns(topic, entries)
    lines = [_row([spec.column or spec.name for spec in columns]), _row(["---" for _ in columns])]
    for entry in entries:
        cells = [cell(spec, entry.get(spec.name), topic.key, base) for spec in columns]
        cells[0] = f'<span id="{anchor(topic, entry.get(topic.key_field))}"></span>{cells[0]}'
        lines.append(_row(cells))
    return lines


def _row(cells: Sequence[str]) -> str:
    """One table row. An empty cell is written `| |`: markdownlint's compact table style (MD060) refuses two spaces."""
    return "|" + "|".join(f" {text} " if text else " " for text in cells) + "|"


def _schema(topic: Topic) -> list[str]:
    """The topic's schema as a table: field, type, hand-written or extracted, meaning."""
    lines = ["| Field | Type | Hand-written | Meaning |", "| --- | --- | --- | --- |"]
    for spec in topic.field_map().values():
        lines.append(_row([f"`{spec.name}`", spec.kind, "yes" if spec.curated else "", _escape(spec.doc)]))
    return lines


def _group_order(values: list[str]) -> list[str]:
    """Groups in first-seen order (the YAML's order is meaningful), unnamed ones last."""
    order: list[str] = []
    for value in values:
        if value not in order:
            order.append(value)
    return order


def page(reflist: RefList) -> str:
    """The Markdown page of one reference list."""
    topic = reflist.topic
    entries = reflist.resolved()
    lines = [f"# {reflist.title}", "", GENERATED.format(key=topic.key), ""]
    if reflist.about:
        lines += [reflist.about, ""]
    if reflist.complete:
        lines += ['!!! info "What is complete"', ""]
        lines += [("    " + line) if line else "" for line in reflist.complete_text().splitlines()]
        lines.append("")
    lines += [f"{len(entries):,} entries. Data: `research/references/{topic.key}.yaml`.", ""]
    if topic.split and topic.group_by:
        lines += _split_index(reflist)
    elif topic.group_by:
        groups = _group_order([str(entry.get(topic.group_by) or "other") for entry in entries])
        for group in groups:
            members = [entry for entry in entries if str(entry.get(topic.group_by) or "other") == group]
            lines += [f"## {group} {{#{slug(group)}}}", "", f"{len(members):,} entries.", ""]
            lines += table(topic, members)
            lines.append("")
    else:
        lines += ["## Entries", ""]
        lines += table(topic, entries)
        lines.append("")
    evidence = sorted({str(entry.get("evidence")) for entry in entries})
    sources = sorted({str(entry.get("source")) for entry in entries if entry.get("source")})
    lines += ["## Sources and evidence", ""]
    lines += [f"Evidence levels used: {', '.join(evidence)}.", ""]
    if len(sources) <= 12:
        lines += [f"- {_escape(source)}" for source in sources]
    else:
        lines.append(f"{len(sources)} distinct sources; each entry's source is in the YAML.")
    lines += ["", "## Fields", ""]
    lines += _schema(topic)
    return "\n".join(lines).rstrip() + "\n"


def _groups(reflist: RefList) -> list[tuple[str, list[dict[str, Any]]]]:
    """A grouped list's groups in page order, each with its entries (defaults filled in)."""
    group_by = reflist.topic.group_by or ""
    entries = reflist.resolved()
    names = _group_order([str(entry.get(group_by) or "other") for entry in entries])
    return [(name, [entry for entry in entries if str(entry.get(group_by) or "other") == name]) for name in names]


def _split_index(reflist: RefList) -> list[str]:
    """The overview of a split list: one row per group, linking its page."""
    key = reflist.topic.key
    heading = (reflist.topic.group_by or "group").capitalize()
    lines = ["## Pages", "", f"| {heading} | Entries |", "| --- | ---: |"]
    for name, members in _groups(reflist):
        lines.append(f"| [{name}]({key}/{part_name(name)}.md) | {len(members):,} |")
    return [*lines, ""]


def group_pages(reflist: RefList) -> dict[str, str]:
    """A split list's per-group pages, by path below docs/references/ (`flags/level11.md`).

    Each holds one group's table, with the entries' usual anchors; the overview page keeps the prose and the fields.
    A split keeps every page small: a long list in one table is slow to load and to search.
    """
    topic = reflist.topic
    out = {}
    for name, members in _groups(reflist):
        lines = [f"# {reflist.title}: {name}", "", GENERATED.format(key=topic.key), ""]
        lines += [
            f"{len(members):,} of the {len(reflist.entries):,} entries of [{reflist.title}](../{topic.key}.md),",
            f"whose page says what is complete and what each [field](../{topic.key}.md#fields) means.",
            "",
        ]
        lines += table(topic, members, base="../")
        out[f"{topic.key}/{part_name(name)}.md"] = "\n".join(lines).rstrip() + "\n"
    return out


def index(
    reflists: Sequence[RefList], bindings_page: bool, entities_page: bool = False, gaps: Gaps | None = None
) -> str:
    """The index page: what the references are, the lists with their counts, what is still to list, how to contribute.

    `entities_page` links the hand-written Entities page from the introduction; `gaps` adds the "Still to list" table.
    """
    lines = [
        "# Game references",
        "",
        GENERATED.format(key="*"),
        "",
        "Lists of the things in *The Warriors* that scripts, mods and Coney's own code refer to: characters and",
        "their classes, attacks and hats, gangs and the Rumble roster, objects, weapons, items and cars, levels and",
        "what they place (flags, zones, doors, glass, lights), cameras and screen effects, AI goals, unlockables and",
        "statistics, animations, controls and commands, colours, text tags and labels, script constants, sounds,",
        "speech, script events and the names of the files in the game's archive. They play the part FiveM's",
        "[game references](https://docs.fivem.net/docs/game-references/) play for GTA V: a modder looks up the id or",
        "name to pass, an implementer the value to expect.",
        "",
        '**Characters are "humans".** The game calls every person, the player included, a human: scripts create one',
        "with `HuCreate`, the engine updates them all in `Humans_Update`, and most character bindings start with `Hu`.",
        "A human is the game's equivalent of GTA's ped; see [Characters (research)](../research/characters.md).",
        "",
    ]
    if entities_page:
        lines += [
            "**Start with [Entities](entities.md)**: every kind of thing the game has at run time (humans, objects,",
            "cars, flags, cameras, gangs ...), how scripts refer to each, how many there can be, and which lists and",
            "bindings cover it, with the FiveM equivalent of each.",
            "",
        ]
    lines += [
        "Everything here is a name, an id, a number or our own short description, read from the player's own disc by",
        "`coney-tools refs extract` and checked by hand. No game text, script source, model or image from the disc is",
        'copied ([LEGAL.md](repo:LEGAL.md#no-game-data), "Reference lists").',
        "",
        "## Lists",
        "",
        "| List | Entries | What is complete |",
        "| --- | ---: | --- |",
    ]
    for reflist in reflists:
        complete = reflist.complete_text()
        first = complete.split(". ")[0].rstrip(".").replace("\n", " ") if complete else ""
        lines.append(
            f"| [{reflist.topic.nav or reflist.title}]({reflist.topic.key}.md) | {len(reflist.entries):,} | "
            f"{_escape(first)}. |"
        )
    lines += ["", "## Script bindings", ""]
    if bindings_page:
        lines.append("The functions the scripts call are listed in [Script bindings](bindings/index.md).")
    else:
        lines += [
            "The functions the scripts call (956 bindings) get their own masterlist, Script bindings, in this section;",
            "until it lands, see the [roadmap](../roadmap.md#script-mods).",
        ]
    if gaps is not None:
        lines += ["", *_gaps_section(gaps)]
    lines += [
        "",
        "## Images",
        "",
        "Characters, objects, cars, radar icons, particle effects and the lists that name an object (hats, inventory)",
        "may show a thumbnail. Coney renders them itself from the player's disc (`coney --render-references DIR",
        "--names FILE`, [Building](../guides/building.md#reference-images)) as transparent PNGs in",
        "`docs/references/images/`, named after the entry's stable reference name, so the renderer and these lists",
        "agree without a lookup table. Models are 256 x 256; 2D icons and sprites are at most 64 x 64:",
        "",
        "| Lists | Image | File name | Example |",
        "| --- | --- | --- | --- |",
        "| Characters, Character models | the model standing | `characters/<model name>.png`, or `<name hash>.png` for "
        "a model with no recovered name | `characters/warr_re_cv.png` |",
        "| Objects, Hats, Inventory | the object's model | `objects/<name>.png`, the object type name | "
        "`objects/dyn_bat.png` |",
        "| Cars (types) | the undamaged car | `cars/<type name>.png` | `cars/car_osedan.png` |",
        "| Radar icons | the icon at its own size | `radar/icon-<n>.png` | `radar/icon-28.png` |",
        "| Particle effects (traced sprites) | the sprite scaled to fit 64 x 64 | `particles/<name>.png` | "
        "`particles/part_fire.png` |",
        "",
        "`coney-tools refs extract` fills an entry's `image` field when its file exists; a missing image is simply",
        "left out of the table.",
        "",
        "## Contributing",
        "",
        "Edit the YAML in `research/references/`, then run `uv run --project python coney-tools refs render`. The",
        "hand-written fields (who a character is, what a constant means) are kept when the lists are refreshed from",
        "the disc with `coney-tools refs extract`. The schema and rules are in",
        "[Research workflow](../guides/research-workflow.md#reference-lists).",
    ]
    return "\n".join(lines) + "\n"


def _gaps_section(gaps: Gaps) -> list[str]:
    """The "Still to list" section: one row per family of ids or names with no list yet, most useful first."""
    headings = {
        "family": "Family",
        "what": "What it is",
        "source": "Where the ids come from",
        "count": "Count",
        "image": "Image",
        "needs": "What a list needs",
    }
    lines = [
        "## Still to list {#still-to-list}",
        "",
        "Families of ids, names and values that scripts or the `Cfg*` tables use and that have no list yet, the most",
        "useful to a script author first. Counts are from the disc's 467 compiled scripts. *Image* says how an entry",
        "could be illustrated: **model render** (Coney renders the model, as for characters), **icon render** (one",
        "2D icon or sprite of at most 64 x 64 that Coney renders from the disc), **swatch** (a colour the docs draw)",
        "or **none**. The list is `research/references/still-to-list.yaml`; a family that gets its own list leaves",
        "it.",
        "",
    ]
    # Once every family has its own list the table would be empty: say so instead.
    if gaps.families:
        lines += [_row([headings[name] for name in GAP_FIELDS]), _row(["---" for _ in GAP_FIELDS])]
        lines += [_row([_escape(family[name]) for name in GAP_FIELDS]) for family in gaps.families]
    else:
        lines.append("Every family the scripts use has a list now.")
    if gaps.excluded:
        lines += ["", *textwrap.wrap(_escape(gaps.excluded), width=120, break_on_hyphens=False)]
    return lines
